resources:
- name: repo
  type: git
  source:
    url: https://github.com/simonkesh/concourse-journey.git

jobs:
- name: hello-world-job
  plan:
  # Add a get step referencing the resource
  - get: repo
  - task: hello-world-task
    config:
    # Tells Concourse which type of worker this task should run on
      platform: linux
      # This is one way of telling concourse which container image to use for a task
      # We'll explain this more when talking about resources
      image_resource:
        type: registry-image
        source:
          repository: busybox # images are pulled from docker hub by default
          # The command Concourse will run inside a container is echo "Hello world!"
      run:
        path: echo
        args: ["Hello World!"]